# bash profile is executed for login shells
# we include .bashrc, so this is basically stuff that should only be run once

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

#
# Let this rvm shit live here instead of main configuration,
# cuz rvm installer is annoying and re-adds them!
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

### ALIAS ###
alias be='bundle exec'
alias ber='bundle exec rake'
alias ber_staging='bundle exec cap staging rake_exec -s rake_cmd='
alias ber_production='bundle exec cap production rake_exec -s rake_cmd='
alias berdb='bundle exec rake db:drop db:create db:migrate db:seed'
alias reload='source ~/.bashrc'
alias gs='git status'
alias git-log='git log --pretty=format:"%C(yellow)%h%C(reset) %C(green)%ar%C(reset) %C(bold blue)%an%C(reset) %C(red)%d%C(reset) %s" --graph --abbrev-commit --decorate'
alias l='ls -la'
alias closure='java -jar $HOME/Applications/Closure/compiler.jar'
alias linode='$HOME/.open_linode.sh'
alias ssh_tunnel='$HOME/.open_ssh_tunnel.sh'
alias kill_ssh='kill -9 `ps -eo pid,args | grep "ssh " | grep -v "grep" | cut -c1-6`'
alias postgres_start='pg_ctl -D /usr/local/var/postgres -l logfile start'
alias postgres_stop='pg_ctl -D /usr/local/var/postgres -l logfile stop'
alias fr='foreman run '

export EDITOR="subl"
